### ISSUE TITLE
There's Some Light Munging Happening?

### ISSUE THREAD

**Issue by timvisher** [raphaelcosta/tap-pipefy#12]
Generally speaking, `tap`s should munge data as little as possible.
Reviewing the `organization` query for instance I see that we lift the
`organization` object out of the response. That may be appropriate (often
we need to lift pages out of paginated responses, for instance) or it may
not be.

I also see that in `process_table_record` we're adding an `__id` key and
I'm unclear on the purposes of that. Maybe a comment is in order or a
rewrite of that component?

There may be other issues like this.

**Comment by raphaelcosta** [comment]
Fixed on 690578e
