### ISSUE TITLE
README.md updates

### ISSUE THREAD

**Issue by timvisher** [raphaelcosta/tap-pipefy#2]
- I would recommend (although this is not a strict requirement)
  hard-wrapping your markdown files at 72 columns to make diffs more
  meaningful.
- `bash` code snippets should generally not include prompt characters to
  make them easier to copy/paste.
- It would be nice to have a table of contents (possibly managed by
  [doctoc][]).
- This document is much nicer to read than [the template][]. Would you
  mind opening an a PR there to add a Quick start section to it?
- `virtualenv` setup should be rewritten to emphasize the use of `python3
  -m venv` etc as can be found in the [tap template][template issue 3]. If
  -you wanted to take care of adding that so future devs don't run into
  -this problem that'd be awesome as well. :)
- tap run commands like `./tap-pipefy/bin/tap-pipefy --config config.json
  --discover` should be rewritten to assume that the virtualenv has been
  activated.
- The copyright should probably be bumped to 2019?
- The `Extracts the following resources…` section in the opening links to
  at least 3 different documentation sources. Are you sure that's correct?

[the template]: https://github.com/singer-io/singer-tap-template
[template issue 3]: https://github.com/singer-io/singer-tap-template/issues/3
[doctoc]: https://github.com/thlorenz/doctoc

**Comment by raphaelcosta** [comment]
- [X ] I would recommend (although this is not a strict requirement)
- [X ] hard-wrapping your markdown files at 72 columns to make diffs more
- [ X] meaningful.
- [X ] bash code snippets should generally not include prompt characters to
- [X ] make them easier to copy/paste.
- [X ] It would be nice to have a table of contents (possibly managed by
- [X ] doctoc).
- [X ] This document is much nicer to read than the template. Would you
- [X ] mind opening an a PR there to add a Quick start section to it?
- [ ] virtualenv setup should be rewritten to emphasize the use of python3 -m venv etc as can be found in the tap template. If
- [X ] -you wanted to take care of adding that so future devs don't run into
- [X ] -this problem that'd be awesome as well. :)
- [ ] tap run commands like ./tap-pipefy/bin/tap-pipefy --config config.json --discover should be rewritten to assume that the virtualenv has been
- [ ] activated.
- [ ] The copyright should probably be bumped to 2019?
- [ ] The Extracts the following resources… section in the opening links to
- [ ] at least 3 different documentation sources. Are you sure that's correct?
